name: dose_finder1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'dose_finder1') || github.event_name=='workflow_dispatch'"

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GRZ_TOKEN }}

    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test
      run: |
        if [ -f data/output/slots_dep.json ]; then cat data/output/slots_dep.json; fi

    - name: Dose Finder
      run: |
        python3 dose_finder_part.py 0 10
        
    #- uses: stefanzweifel/git-auto-commit-action@v4
      #with:
        #commit_message: Apply automatic changes (dose_finder1)
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        labels: automerge
        token: ${{ secrets.GRZ_TOKEN }}
        title: Auto Pull Request (dose_finder1)
