name: dose_finder4

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre_job:
    continue-on-error: true
    runs-on: ubuntu-latest 
    if: ${{ (contains(github.event.head_commit.message, 'dose_finder4') || github.event_name=='workflow_dispatch' || github.event_name=='schedule') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '[]' #'["pull_request", "workflow_dispatch", "schedule"]'
          
  build:
    needs: pre_job
    if: ${{ (needs.pre_job.outputs.should_skip != 'true') && (contains(github.event.head_commit.message, 'dose_finder4') || github.event_name=='workflow_dispatch' || github.event_name=='schedule') }}
    runs-on: ubuntu-latest
    #if: "contains(github.event.head_commit.message, 'dose_finder4') || github.event_name=='workflow_dispatch'"

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GRZ_TOKEN2 }}

    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test
      run: |
        if [ -f data/output/slots_dep.json ]; then cat data/output/slots_dep.json; fi
        
    - name: Configure locales
      run: |
        sudo locale-gen fr_FR.UTF-8
        sudo update-locale LANG=fr_FR.UTF-8

    - name: Dose Finder
      run: |
        python3 dose_finder_part.py 31 40
        
    #- uses: stefanzweifel/git-auto-commit-action@v4
      #with:
        #commit_message: Apply automatic changes (dose_finder1)
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        labels: automerge
        token: ${{ secrets.GRZ_TOKEN2 }}
        title: Auto Pull Request (dose_finder4)
        branch: create-pull-request-dose-finder-4
