name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test
      run: |
        if [ -f data/output/slots_dep.json ]; then cat data/output/slots_dep.json; fi

    - name: Dose Finder
      run: |
        python3 dose_finder.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        labels: automerge
        token: ${{ secrets.GRZ_TOKEN }}
